### ISSUE TITLE
Typedef of datatype decl to the tag name is currently assumed

### ISSUE THREAD

**Issue by ericvanwyk** [melt-umn/ableC-algebraic-data-types#1]
This is because within the adtDecls, the refIds are erroneously different from the ones placed in the global environment, so this is done as a temporary workaround. I'm not sure what is causing this. 

This is copied over from the corresponding repo on github.umn.edu, which is now obsolete.

**Comment by krame505** [comment]
I fixed this quite a while ago, closing.
